spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
logging:
  level:
    com.shyb: info
  file: ../springboot.log
mybatis:
  mapper-locations: classpath:mappers/**/*.xml


---
spring:
  profiles: dev
  datasource:
    username: root
    password: yali
    url: jdbc:mysql://localhost:3306/boqinfund?characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&useSSL=true&zeroDateTimeBehavior=convertToNull&autoReconnect = true
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/boqinfund?characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&useSSL=true&zeroDateTimeBehavior=convertToNull&autoReconnect = true
    username: root
    password: 123456
